name: Build CC CLI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Get tag version
        id: version
        run: |
          # Extract the version number by removing the 'v' prefix
          ref="${GITHUB_REF_NAME}"
          v="${ref#v}"
          echo "Extracted version: $v"
          echo "version=$v" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          cd src && env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X 'main.version=${{ steps.version.outputs.version }}' -X 'main.commit=$(git describe --tags --always --long)' -X 'main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o dist/cccli-${{ matrix.os }}-${{ matrix.arch }} ./cmd

      - name: Rename Windows Executables
        if: matrix.os == 'windows'
        run: |
          mv src/dist/cccli-windows-${{ matrix.arch }} src/dist/cccli-windows-${{ matrix.arch }}.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: src/dist/*
